import { Gabarito } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";

const gabarito = Gabarito({
  subsets: ["latin"],
  variable: "--custom-font-gabarito",
});

export const metadata = {
  title: "AnimeList",
  description: "Generated by Z4FL",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gabarito.className} bg-color-dark`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
